### ISSUE TITLE
Cover mysql replication

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/andariel-monitoring#3]
We need to be sure that mysql replication is running from master to slave node 
Basically not running means sev2 ticket.
Running: everything is fine.

It might be hard to tell running/not running, so basically we can measure the lag for binlogs to appear on slave.
< 100 ms fine
else sev3
or if > 5 s sev2

**Comment by StefanTurbine** [comment]
done but not tested yet. need to make ui available on dev first to test it properly

**Comment by StefanTurbine** [comment]
done and working!
